### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by kuizi-brother** [alltobebetter/HybridMedNet#1]
您好 方便添加一下联系方式吗 有代码相关问题想要咨询一下

**Comment by alltobebetter** [comment]
您好，非常感谢您的关注，但是很遗憾这是个测试项目，并没有完整的审批和修改，我们做这个项目的目的也只是临时决策，具体的项目可能会在几个月后开始讨论
但如果您想联系我的话，me@aibob.top
